projects:
  serverlesscontactfor:
    schemaPath: amplify/backend/api/serverlesscontactfor/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
